# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Test

on:
  push:
  pull_request:

jobs:
  validate:
    concurrency: compile-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '14']
    name: Lint test on Node ${{ matrix.node }}
    steps:
      - run: echo ${{github.ref}}

      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - name: Install
        run: | # Install packages
         npm install --prefer-offline --no-audit
      - name: Lint
        run: |
          npm run lint
      - name: Test
        run: |
          npm run test

  build:
    needs: validate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '14' ]
    name: Build and Deploy on Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - name: Install #run on lint step (Which is cached)
        run: | # Install packages
          npm install --prefer-offline --no-audit
      - name: Build 🔧
        run: | # build the files
          npm run build
      - name: Build storybook 🔧
        run: | # build the Storybook files
          npm run build-storybook

      - name: setup Package
        run: |
          ls -ltr
          mkdir -p ./target/docs
          cp -r ./storybook-static ./target/docs
          cp -r ./dist/* ./target/.

      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: ./target

#      - name: Deploy 🚀
#        uses: JamesIves/github-pages-deploy-action@3.6.2
#        with:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          BRANCH: gh-pages # The branch the action should deploy to.
#          FOLDER: storybook-static # The folder that the build-storybook script generates files.
#          CLEAN: true # Automatically remove deleted files from the deploy branch
#          TARGET_FOLDER: docs # The folder that we serve our Storybook files from
